### ISSUE TITLE
Markdown: deal with bold + italics

### ISSUE THREAD

**Issue by ghost** [tpoisot/writer-syntax#6]
Light Viridis.

When doing `*__bold-italic text__*` the syntax highlitghting works perfectly as expected.
But if I do `***bold-italic text***` it doesn’t. Is there a way to fix this? I noticed that the One Light theme can’t either.

**Comment by tpoisot** [comment]
This is  because both `language-gfm` and `language-markdown` have poor detection of bold/italics. I think your solution is generally the way to go, although it requires to mix `_` and `*`.

**Comment by ghost** [comment]
Thank’s anyway, I’ll try to look at the language packages
