### ISSUE TITLE
Bright color scheme

### ISSUE THREAD

**Issue by rafgraph** [tpoisot/writer-syntax#9]
I really liked the bright color scheme pre v0.33 (for use with javascript). With the upgrade it has become too saturated for my tastes. Is it possible to access that color scheme or bring it back under another name? I reverted to v0.29.1 for the time being. Thanks.

**Comment by tpoisot** [comment]
0.34.3 has the `Original` color scheme from up to 0.29.x

**Comment by rafgraph** [comment]
Thanks!
